[features]
seeds = false
[programs.localnet]
solana_twitter = "FWktdUkhQ8SevB6NWYvz664ecKbsE2kcf11UZiXNa3Jp"

[programs.devnet]
solana_twitter = "FWktdUkhQ8SevB6NWYvz664ecKbsE2kcf11UZiXNa3Jp"

[programs.mainnet]
solana_twitter = "FWktdUkhQ8SevB6NWYvz664ecKbsE2kcf11UZiXNa3Jp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/anmol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

[workspace]
types = "app/src/idl/"